// Generated by LiveScript 1.3.1
(function(){
  var root, refreshMessages, atBottom, out$ = typeof exports != 'undefined' && exports || this, slice$ = [].slice;
  root = typeof exports != 'undefined' && exports !== null ? exports : this;
  root.maxidx = 0;
  root.firstload = true;
  out$.refreshMessages = refreshMessages = function(){
    return $.getJSON('/messages?idx=' + root.maxidx, function(messages){
      var shouldscroll, i$, len$, ref$, type, text, time, idx, lines, j$, len1$, line;
      shouldscroll = atBottom() || root.firstload;
      root.firstload = false;
      for (i$ = 0, len$ = messages.length; i$ < len$; ++i$) {
        ref$ = messages[i$], type = ref$.type, text = ref$.text, time = ref$.time, idx = ref$.idx;
        root.maxidx = Math.max(root.maxidx, idx + 1);
        lines = text.split('\n');
        if (lines[lines.length - 1] === '') {
          lines = slice$.call(lines, 0, -1);
        }
        for (j$ = 0, len1$ = lines.length; j$ < len1$; ++j$) {
          line = lines[j$];
          switch (type) {
          case 'stdout':
            $('#messages').append($('<div>').append([
              $('<div>').css({
                'background-color': '#BFD2FF',
                'margin-right': '5px',
                'display': 'inline-block'
              }).text(new Date(time).toString()), $('<div>').css({
                'display': 'inline-block'
              }).text(line)
            ]));
            break;
          case 'stderr':
            $('#messages').append($('<div>').append([
              $('<div>').css({
                'background-color': '#BFD2FF',
                'margin-right': '5px',
                'display': 'inline-block'
              }).text(new Date(time).toString()), $('<span>').css({
                'display': 'inline-block',
                'background-color': 'yellow'
              }).text(line)
            ]));
          }
        }
      }
      if (shouldscroll) {
        window.scrollTo(0, $(document).height() - window.innerHeight);
      }
    });
  };
  out$.atBottom = atBottom = function(){
    return window.scrollY >= ($(document).height() - window.innerHeight) - 100;
  };
  $(document).ready(function(){
    return setInterval(refreshMessages, 1000);
  });
}).call(this);
